/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddMPAForm: typeof import('./components/mpa/AddMPAForm.vue')['default']
    AddUserForm: typeof import('./components/users/AddUserForm.vue')['default']
    AppHeader: typeof import('./components/ui/AppHeader.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    CheckboxField: typeof import('./components/ui/fields/CheckboxField.vue')['default']
    ConfirmModal: typeof import('./components/ui/ConfirmModal.vue')['default']
    ContextMenu: typeof import('./components/ui/ContextMenu.vue')['default']
    ContextSubMenu: typeof import('./components/ui/ContextSubMenu.vue')['default']
    Details: typeof import('./components/ui/Details.vue')['default']
    Dropdown: typeof import('./components/ui/Dropdown.vue')['default']
    DropdownField: typeof import('./components/ui/fields/DropdownField.vue')['default']
    FileUpload: typeof import('./components/ui/FileUpload.vue')['default']
    FileUploadField: typeof import('./components/ui/fields/FileUploadField.vue')['default']
    FilterModal: typeof import('./components/mpa/MapComponents/FilterModal.vue')['default']
    Form: typeof import('./components/ui/Form.vue')['default']
    FormBuilder: typeof import('./components/ui/form/FormBuilder.vue')['default']
    GenericDataTable: typeof import('./components/ui/GenericDataTable.vue')['default']
    InputText: typeof import('./components/ui/InputText.vue')['default']
    InputTextField: typeof import('./components/ui/fields/InputTextField.vue')['default']
    Loading: typeof import('./components/ui/Loading.vue')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    LoginModal: typeof import('./components/auth/LoginModal.vue')['default']
    MapDashboard: typeof import('./components/mpa/MapDashboard.vue')['default']
    MapModal: typeof import('./components/ui/MapModal.vue')['default']
    MPADetails: typeof import('./components/mpa/MPADetails.vue')['default']
    MpaDrawer: typeof import('./components/mpa/MapComponents/MpaDrawer.vue')['default']
    MPAEditForm: typeof import('./components/mpa/MPAEditForm.vue')['default']
    MPAForm: typeof import('./components/mpa/MPAForm.vue')['default']
    MPAList: typeof import('./components/mpa/MPAList.vue')['default']
    MultiStepForm: typeof import('./components/ui/form/MultiStepForm.vue')['default']
    PasswordField: typeof import('./components/ui/PasswordField.vue')['default']
    PasswordTextField: typeof import('./components/ui/fields/PasswordTextField.vue')['default']
    PinDrawer: typeof import('./components/mpa/MapComponents/PinDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectBox: typeof import('./components/ui/SelectBox.vue')['default']
    SignupForm: typeof import('./components/auth/SignupForm.vue')['default']
    Switch: typeof import('./components/ui/Switch.vue')['default']
    SwitchField: typeof import('./components/ui/fields/SwitchField.vue')['default']
    Table: typeof import('./components/ui/Table.vue')['default']
    UserDetails: typeof import('./components/users/UserDetails.vue')['default']
    UserForm: typeof import('./components/users/UserForm.vue')['default']
    UserIcon: typeof import('./components/ui/UserIcon.vue')['default']
    UserList: typeof import('./components/users/UserList.vue')['default']
    UserMenu: typeof import('./components/auth/UserMenu.vue')['default']
  }
}
