/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/Button.vue')['default']
    FileUpload: typeof import('./components/ui/FileUpload.vue')['default']
    FilterModal: typeof import('./components/mpa/MapComponents/FilterModal.vue')['default']
    Form: typeof import('./components/ui/Form.vue')['default']
    FormBuilder: typeof import('./components/ui/form/FormBuilder.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('./components/ui/InputText.vue')['default']
    Loading: typeof import('./components/ui/Loading.vue')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    MapDashboard: typeof import('./components/mpa/MapDashboard.vue')['default']
    MPADetails: typeof import('./components/mpa/MPADetails.vue')['default']
    MpaDrawer: typeof import('./components/mpa/MapComponents/MpaDrawer.vue')['default']
    MPAForm: typeof import('./components/mpa/MPAForm.vue')['default']
    MPAList: typeof import('./components/mpa/MPAList.vue')['default']
    MultiStepForm: typeof import('./components/ui/form/MultiStepForm.vue')['default']
    PasswordField: typeof import('./components/ui/PasswordField.vue')['default']
    PinDrawer: typeof import('./components/mpa/MapComponents/PinDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectBox: typeof import('./components/ui/SelectBox.vue')['default']
    SignupForm: typeof import('./components/auth/SignupForm.vue')['default']
    Switch: typeof import('./components/ui/Switch.vue')['default']
    Table: typeof import('./components/ui/Table.vue')['default']
    UserDetails: typeof import('./components/users/UserDetails.vue')['default']
    UserForm: typeof import('./components/users/UserForm.vue')['default']
    UserList: typeof import('./components/users/UserList.vue')['default']
  }
}
